all:
	g++ main.cpp\
		MonoReverseInterpolator.cpp\
		ReverseInterpolator.cpp\
		../PolynomialInterpolation/InterpolationalCalculator.cpp\
		../PolynomialInterpolation/LagrangePolynom.cpp\
		../PolynomialInterpolation/NewtonPolynom.cpp\
		../NonLinearEquations/EquationSolver.cpp\
		-I../PolynomialInterpolation\
		-I../NonLinearEquations\
		-o ../build/reverse_interpolator